#os: SharePoint 2013

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - nuget restore %solutionFile%

build:
  project: spec.sln
  parallel: false
  verbosity: minimal
