#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - dotnet restore src/spec.sln

build:
  project: src\spec.sln
  parallel: false
  verbosity: minimal
  
configuration: Release
platform: Any CPU
