#os: SharePoint 2013

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - nuget restore src\spec.sln

build:
  project: src\spec.sln
  parallel: false
  verbosity: minimal
